services:
  # PostgreSQL база данных
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: funnel_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Приложение
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/funnel_dev"
      SHOPIFY_API_KEY: ${SHOPIFY_API_KEY}
      SHOPIFY_API_SECRET: ${SHOPIFY_API_SECRET}
      SCOPES: "write_products,read_products,write_discounts,read_discounts,write_orders,read_orders,write_themes,read_themes"
      SHOPIFY_APP_URL: "https://localhost:3000"
      NODE_ENV: "production"
      HOST: "0.0.0.0"
      PORT: "3000"
    depends_on:
      - postgres
    command: sh -c "npx prisma migrate deploy && npm run start"

volumes:
  postgres_data:
